#### ****Import Dependencies****

In [2]:
!pip install stable-baselines3\[extra\]

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 681.7 kB/s eta 0:00:00MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 434.7/434.7 kB 1.5 MB/s eta 0:00:00m eta 0:00:010:01:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached Farama_Notifications-0.0.4-py3-none-any.whl.metadata (558 bytes)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 1.3 MB/s eta 0:00:001.4 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 1.5 MB/s eta 0:00:00m eta 0:00:010:01:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 MB 3.8 MB/s eta 0:00:00m eta 0:00:010:00:010m
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.8/54.8 MB 3.8 MB/s eta 0:00:00m eta 0:00:010:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 6.5 MB/s eta 0:00:00m eta 0:00:010:01:01
   ━━━━━━━━━━━━━━

In [5]:
pip install gym\[extra\]

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.7/721.7 kB 2.5 MB/s eta 0:00:00 MB/s eta 0:00:01:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gym: filename=gym-0.26.2-py3-none-any.whl size=827623 sha256=1bd0cff539a7624c2c0c06b17422ca289ce608190ca7e4326914a0d7c1eb25ba
  Stored in directory: /Users/mohana25/Library/Caches/pip/wheels/af/2b/30/5e78b8b9599f2a2286a582b8da80594f654bf0e18d825a4405
Successfully built gym
Note: you may need to restart the kernel to use updated packages.


In [1]:
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

#### ***Load Environment***

In [2]:
environment_name = 'CartPole-v1'
env = gym.make(environment_name, render_mode = "human")

In [48]:
environment_name

'CartPole-v1'

In [3]:
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done :
        env.render()
        if done == True :
            env.reset()
        action = env.action_space.sample()
        temp = env.step(action)
        n_state = temp[0]
        reward = temp[1]
        done = temp[2]
        info = temp[3]
        score += reward
        print("Episode : {}, Score : {}".format(episode, score))

/Users/mohana25/Library/Python/3.9/lib/python/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


Episode : 1, Score : 1.0
Episode : 1, Score : 2.0
Episode : 1, Score : 3.0
Episode : 1, Score : 4.0
Episode : 1, Score : 5.0
Episode : 1, Score : 6.0
Episode : 1, Score : 7.0
Episode : 1, Score : 8.0
Episode : 1, Score : 9.0
Episode : 1, Score : 10.0
Episode : 1, Score : 11.0
Episode : 1, Score : 12.0
Episode : 1, Score : 13.0
Episode : 1, Score : 14.0
Episode : 1, Score : 15.0
Episode : 1, Score : 16.0
Episode : 1, Score : 17.0
Episode : 1, Score : 18.0
Episode : 1, Score : 19.0
Episode : 1, Score : 20.0
Episode : 1, Score : 21.0
Episode : 1, Score : 22.0
Episode : 1, Score : 23.0
Episode : 1, Score : 24.0
Episode : 1, Score : 25.0
Episode : 1, Score : 26.0
Episode : 1, Score : 27.0
Episode : 1, Score : 28.0
Episode : 1, Score : 29.0
Episode : 2, Score : 1.0
Episode : 2, Score : 2.0
Episode : 2, Score : 3.0
Episode : 2, Score : 4.0
Episode : 2, Score : 5.0
Episode : 2, Score : 6.0
Episode : 2, Score : 7.0
Episode : 2, Score : 8.0
Episode : 2, Score : 9.0
Episode : 2, Score : 10.0
Epis

In [7]:
env.step(action)

(array([-0.3373942, -1.0192875,  0.4367937,  1.8024607], dtype=float32),
 0.0,
 True,
 False,
 {})

In [8]:
env.close()

#### ***Understanding Environment***

In [16]:
env.action_space

Discrete(2)

In [18]:
env.action_space.sample()

1

In [19]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [20]:
env.observation_space.sample()

array([ 2.8118851e+00,  3.1841572e+38, -2.1160609e-01,  2.1250956e+38],
      dtype=float32)

#### ***Training our RL model***

In [9]:
log_path = os.path.join('Training','Logs')

In [6]:
log_path

'Training/Logs'

In [10]:
env = gym.make(environment_name, render_mode='human')
env = DummyVecEnv([lambda : env])
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log = log_path)

/Users/mohana25/Library/Python/3.9/lib/python/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(


Using cpu device


In [9]:
model.learn(total_timesteps=20000)

Logging to Training/Logs/PPO_10


/Users/mohana25/Library/Python/3.9/lib/python/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


-----------------------------
| time/              |      |
|    fps             | 45   |
|    iterations      | 1    |
|    time_elapsed    | 44   |
|    total_timesteps | 2048 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 44           |
|    iterations           | 2            |
|    time_elapsed         | 92           |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0071293865 |
|    clip_fraction        | 0.0654       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.687       |
|    explained_variance   | 0.000581     |
|    learning_rate        | 0.0003       |
|    loss                 | 7.55         |
|    n_updates            | 10           |
|    policy_gradient_loss | -0.00956     |
|    value_loss           | 54           |
------------------------------------------
----------------

#### ***Save and Reload model***

In [11]:
PPO_path = os.path.join('Training','Saved Models','PPO_Model_cartpole')

In [12]:
model.save(PPO_path)

#### ***Evaluating model***

In [11]:
evaluate_policy(model, env, n_eval_episodes = 10, render = True)

/Users/mohana25/Library/Python/3.9/lib/python/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(
/Users/mohana25/Library/Python/3.9/lib/python/site-packages/gym/utils/passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(10.5, 1.02469507659596)

In [12]:
env.close()

#### ***Test Model***

In [15]:
episodes = 5
for episode in range(1, episodes+1):
    obs = env.reset()[0]
    done = False
    score = 0
    
    while not done :
        env.render(mode='human')
        action = model.predict(obs)
        temp = env.step(action)
        n_state = temp[0]
        reward = temp[1]
        done = temp[2]
        info = temp[3]
        score += reward
        print("Episode : {}, Score : {}".format(episode, score))

Episode : 1, Score : [1.]
Episode : 1, Score : [2.]
Episode : 1, Score : [3.]
Episode : 1, Score : [4.]
Episode : 1, Score : [5.]
Episode : 1, Score : [6.]
Episode : 1, Score : [7.]
Episode : 1, Score : [8.]
Episode : 1, Score : [9.]
Episode : 1, Score : [10.]
Episode : 1, Score : [11.]
Episode : 1, Score : [12.]
Episode : 1, Score : [13.]
Episode : 1, Score : [14.]
Episode : 1, Score : [15.]
Episode : 1, Score : [16.]
Episode : 1, Score : [17.]
Episode : 1, Score : [18.]
Episode : 1, Score : [19.]
Episode : 1, Score : [20.]
Episode : 1, Score : [21.]
Episode : 1, Score : [22.]
Episode : 1, Score : [23.]
Episode : 1, Score : [24.]
Episode : 1, Score : [25.]
Episode : 1, Score : [26.]
Episode : 1, Score : [27.]
Episode : 1, Score : [28.]
Episode : 1, Score : [29.]
Episode : 1, Score : [30.]
Episode : 1, Score : [31.]
Episode : 1, Score : [32.]
Episode : 1, Score : [33.]
Episode : 1, Score : [34.]
Episode : 1, Score : [35.]
Episode : 1, Score : [36.]
Episode : 1, Score : [37.]
Episode : 

In [8]:
env.close()

In [16]:
env.step(action)

(array([[-0.04002902, -0.16762948,  0.02754384,  0.3348883 ]],
       dtype=float32),
 array([1.], dtype=float32),
 array([False]),
 [{'TimeLimit.truncated': False}])

#### ***Adding Callback at Training Stage*** ####

In [31]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [33]:
save_path = os.path.join('Training', 'Saved Models')
stop_callback = StopTrainingOnRewardThreshold(reward_threshold = 200, verbose = 1)
eval_callback = EvalCallback(env,
                             callback_on_new_best=stop_callback,
                             eval_freq = 10000,
                             best_model_save_path = save_path,
                             verbose = 1)

In [34]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log = log_path)

Using cpu device


In [36]:
model.learn(total_timesteps = 20000, callback = eval_callback)

Logging to Training/Logs/PPO_9
-----------------------------
| time/              |      |
|    fps             | 41   |
|    iterations      | 1    |
|    time_elapsed    | 49   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 41          |
|    iterations           | 2           |
|    time_elapsed         | 97          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009409696 |
|    clip_fraction        | 0.101       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.0115     |
|    learning_rate        | 0.0003      |
|    loss                 | 7.49        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0157     |
|    value_loss           | 52.7        |
-----------------------------------------
---

/Users/mohana25/Library/Python/3.9/lib/python/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Eval num_timesteps=10000, episode_reward=245.60 +/- 97.55
Episode length: 245.60 +/- 97.55
-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 246         |
|    mean_reward          | 246         |
| time/                   |             |
|    total_timesteps      | 10000       |
| train/                  |             |
|    approx_kl            | 0.007653229 |
|    clip_fraction        | 0.0759      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.611      |
|    explained_variance   | 0.317       |
|    learning_rate        | 0.0003      |
|    loss                 | 32.9        |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0176     |
|    value_loss           | 64.3        |
-----------------------------------------
New best mean reward!
Stopping training because the mean reward 245.60  is above the threshold 200
